# Generated by Django 4.2.14 on 2024-08-10 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quot_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company_details',
        ),
    ]
